install:
  - sudo apt update
  - sudo apt install liblbfgs-dev

script:
  - ./autogen.sh
  - ./configure --prefix=$HOME/local
  - make
  - make check
  - make install

after_success:
- $HOME/local/bin/crfsuite -h
